### ISSUE TITLE
Why is derived GPG key discouraged?

### ISSUE THREAD

**Issue by MarcCoquand** [fishinthecalculator/sops-guix#3]
Heya! Thanks for building this incredible tool.

The documentation writes

> By setting generate-key? to #t in sops-service-configuration a GPG key will be automatically derived for you from your system's /etc/ssh/ssh_host_rsa_key and added to the configured keyring. It is discouraged to do so and you are more than encouraged to autonomally provide a key in your configured keyring.

Why is this the case? Isn't it easier to use ssh-to-pgp tool like encouraged in sops-nix?

**Comment by fishinthecalculator** [comment]
Its easier but you have less control on the key, for example you could have a requirement to rotate it periodically. You can certainly enable it once, deploy your configuration, and turning it off and handling it from there, but it may not be the best default choice imho. Maybe I could rephrase that avoiding to discourage the usage but just be aware what risks could be involved?

**Comment by MarcCoquand** [comment]
Thanks for the explanation, that makes a lot of sense.

I think it is good to discourage the use of it. With security packages
it is really good to be explicit about what the user should or should
not do IMO. I think it is very good to also explain why in the text, so
that users can make up their own mind.

Nix-sops also encourages something else, thus I wanted to understand the
logic.

**Comment by fishinthecalculator** [comment]
No problem, I'm closing this. Let me know if I can clarify or help any further!
